# Utiliser une image de base de Python
FROM python:3.9-slim

# Définir le répertoire de travail dans le conteneur
WORKDIR /code

# Copier le fichier des dépendances
COPY requirements.txt /code/

# Installer les dépendances
RUN pip install -r requirements.txt

# Copier le code de l'application dans le conteneur
COPY . /code/

# Définir la commande par défaut pour lancer l'application
CMD ["python", "manage.py", "runserver", "0.0.0.0:8001"]
